import Head from 'next/head'
import FeedbackForm from '../components/FeedbackForm/FeedbackForm'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ maxWidth: '500px', width: '100%' }}>
          <FeedbackForm />
        </div>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}
